---
title: "consumption"
author: "Kevin Wang"
date: "Jan 2020"
output: html_document
---

```{r}
library(perturb)
library(tidyverse)
library(ggcorrplot)
library(car)
library(mcvis)


data(consumption)
X=consumption[,-1] ## Remove year variable
ct1 = X[,1] ## Get the consumption column
ct1 = ct1[-28] ## Remove the last obs
X=cbind(X[-1,],ct1) ## Add back the lagged consumption column

glimpse(X)

ggcorrplot(cor(X), 
          type = "upper",
           outline.col = "white",
          lab = TRUE, 
          lab_size = 8, 
          tl.cex = 20)
```


# Scatter plot 
```{r, fig.width = 6, fig.height = 6}
setEPS()
postscript("figures/Fig5.eps", width = 6, height = 6)
pairs(X, lower.panel = CPOP::panel_cor)
dev.off()
```


# VIF
```{r}
vif(lm(cons ~ ., data=X))
```


# mcvis

```{r}
set.seed(5)
mcvis_result = mcvis(X = X[, -which(colnames(X) == "cons")], standardise_method = "studentise") ## Remove consumption column in computing mcvis
mcvis_result$MC


setEPS()
postscript("figures/Fig3.eps", fonts=c("serif", "Palatino"), width = 4.5, height = 4)
plot(mcvis_result, eig.max = 4)
dev.off()

plot(mcvis_result, eig.max = 4)
ggplot(mcvis_result)
```


# Session info 
```{r}
sessionInfo()
```

